type StudentsTable = {
  id: number;
  country: string;
  name: string;
  teacher: string;
  status: string;
  tarif: string;
  balance: string;
  paymentBy: string;
  lastSesia: string;
  totalTime: string;
  languages: string[];
  gameCount: string;
  gamesMoneyCount: string;
  tokenCount: string;
};

const studentarray: StudentsTable[] = [
  {
    id: 1,
    country: "ukraine",
    name: "natalia",
    teacher: "pavlo",
    status: "profi",
    tarif: "200",
    balance: "8000",
    paymentBy: "10.06.2025",
    lastSesia: "15.09.2023",
    totalTime: "256",
    languages: ["EN-UA", "ES-UA"],
    gameCount: "15",
    gamesMoneyCount: "6000",
    tokenCount: "10",
  },
  {
    id: 2,
    country: "usa",
    name: "john",
    teacher: "mary",
    status: "beginner",
    tarif: "150",
    balance: "5000",
    paymentBy: "20.08.2025",
    lastSesia: "12.11.2023",
    totalTime: "120",
    languages: ["EN", "FR"],
    gameCount: "10",
    gamesMoneyCount: "4000",
    tokenCount: "8",
  },
  {
    id: 3,
    country: "germany",
    name: "anna",
    teacher: "thomas",
    status: "intermediate",
    tarif: "180",
    balance: "6000",
    paymentBy: "15.07.2025",
    lastSesia: "18.10.2023",
    totalTime: "180",
    languages: ["DE", "EN"],
    gameCount: "12",
    gamesMoneyCount: "5000",
    tokenCount: "9",
  },
  {
    id: 4,
    country: "france",
    name: "pierre",
    teacher: "sophie",
    status: "advanced",
    tarif: "220",
    balance: "9000",
    paymentBy: "05.05.2025",
    lastSesia: "20.12.2023",
    totalTime: "300",
    languages: ["FR", "EN"],
    gameCount: "20",
    gamesMoneyCount: "8000",
    tokenCount: "15",
  },
  {
    id: 5,
    country: "italy",
    name: "giulia",
    teacher: "marco",
    status: "profi",
    tarif: "250",
    balance: "10000",
    paymentBy: "30.09.2025",
    lastSesia: "25.03.2023",
    totalTime: "400",
    languages: ["IT", "EN"],
    gameCount: "25",
    gamesMoneyCount: "10000",
    tokenCount: "20",
  },
  {
    id: 6,
    country: "spain",
    name: "juan",
    teacher: "isabella",
    status: "beginner",
    tarif: "150",
    balance: "4500",
    paymentBy: "12.08.2025",
    lastSesia: "10.10.2023",
    totalTime: "90",
    languages: ["ES", "EN"],
    gameCount: "8",
    gamesMoneyCount: "3000",
    tokenCount: "6",
  },
  {
    id: 7,
    country: "russia",
    name: "olga",
    teacher: "sergei",
    status: "intermediate",
    tarif: "180",
    balance: "7000",
    paymentBy: "25.07.2025",
    lastSesia: "15.11.2023",
    totalTime: "150",
    languages: ["RU", "EN"],
    gameCount: "10",
    gamesMoneyCount: "4000",
    tokenCount: "8",
  },
  {
    id: 8,
    country: "japan",
    name: "hiroshi",
    teacher: "yuki",
    status: "advanced",
    tarif: "220",
    balance: "8500",
    paymentBy: "08.04.2025",
    lastSesia: "22.12.2023",
    totalTime: "280",
    languages: ["JA", "EN"],
    gameCount: "18",
    gamesMoneyCount: "7000",
    tokenCount: "12",
  },
  {
    id: 9,
    country: "china",
    name: "mei",
    teacher: "li",
    status: "profi",
    tarif: "250",
    balance: "9500",
    paymentBy: "15.10.2025",
    lastSesia: "18.03.2023",
    totalTime: "350",
    languages: ["ZH", "EN"],
    gameCount: "22",
    gamesMoneyCount: "9000",
    tokenCount: "18",
  },
  {
    id: 10,
    country: "south korea",
    name: "jin",
    teacher: "ji-yoon",
    status: "beginner",
    tarif: "150",
    balance: "4000",
    paymentBy: "20.09.2025",
    lastSesia: "12.11.2023",
    totalTime: "100",
    languages: ["KO", "EN"],
    gameCount: "7",
    gamesMoneyCount: "3500",
    tokenCount: "5",
  },
  {
    id: 11,
    country: "brazil",
    name: "carlos",
    teacher: "ana",
    status: "intermediate",
    tarif: "180",
    balance: "5500",
    paymentBy: "10.08.2025",
    lastSesia: "20.10.2023",
    totalTime: "200",
    languages: ["PT", "EN"],
    gameCount: "14",
    gamesMoneyCount: "4500",
    tokenCount: "10",
  },
  {
    id: 12,
    country: "australia",
    name: "emma",
    teacher: "liam",
    status: "advanced",
    tarif: "220",
    balance: "8800",
    paymentBy: "05.03.2025",
    lastSesia: "25.12.2023",
    totalTime: "320",
    languages: ["EN", "AU"],
    gameCount: "16",
    gamesMoneyCount: "7500",
    tokenCount: "14",
  },
];

export default studentarray;
